### ISSUE TITLE
Error thrown when uploading .txt files

### ISSUE THREAD

**Issue by dpuccetti-flywheel** [scitran/api#88] opened 2015-12-07 22:54 UTC
Uploading a text file throws this error:

```
Traceback (most recent call last):
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "./api/api.py", line 126, in dispatcher
    rv = router.default_dispatcher(request, response)
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "./api/base.py", line 125, in dispatch
    return super(RequestHandler, self).dispatch()
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/handlers/listhandler.py", line 367, in post
    file_store = files.FileStore(self.request, tempdir_path, filename=kwargs.get('name'))
  File "./api/files.py", line 77, in __init__
    self.hash = self.received_file.get_hash()
AttributeError: 'cStringIO.StringO' object has no attribute 'get_hash'
```
Image (.png) files work just fine.

**Comment by kofalt** [comment] 2015-12-08 17:32
My guess is that webapp2 or similar is trying to be too clever, and automatically hands us a string object rather than a file. I'm able to reproduce this uploading a bval file.

Assigning to @rentzso since he's probably closest to this one.

**Closed** 2015-12-09 23:33 UTC
